name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.x"
          channel: "stable"

      - name: Check formatting
        run: flutter format --dry-run --set-exit-if-changed lib

      - name: Analyze
        run: flutter analyze --pub

      - name: Test
        run: flutter test --coverage

      - name: Build APK with Flutter
        run: flutter build apk --profile --flavor dev --no-shrink

      - name: Save APK
        uses: actions/upload-artifact@v1
        with:
          name: photoprism-apk
          path: build/app/outputs/apk/dev/profile/

  package:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.x"
          channel: "stable"
      - run: flutter format --dry-run --set-exit-if-changed lib
      - run: flutter analyze
      - run: flutter pub get
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
      - env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: echo "$KEY_JKS" | base64 -d > key.jks && flutter build apk --flavor prod --no-shrink
      - uses: actions/upload-artifact@v1
        with:
          name: photoprism-apk
          path: build/app/outputs/apk/prod/release/

  release:
    needs: package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: photoprism-apk
      - run: mv photoprism-apk/app-prod-release.apk photoprism.apk
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development CI Build"
          files: photoprism.apk
